version: '3'
services:
  frontend:
    build: frontend/
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/frontend/src
    networks:
      - rede-virtual-1
  backend:
    build: backend/
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1
    restart: on-failure
    networks:
      - rede-virtual-2
volumes:
  banco-de-dados:

networks:
  rede-virtual-1:
  rede-virtual-2:  